export const P = '#8B5CF6';      // primary purple
export const P_DARK = '#7C3AED';
export const P_LIGHT = '#EDE9FE';
export const P_MID = '#A78BFA';
export const BG = '#F8F7FF';
export const CARD = '#FFFFFF';
export const TEXT = '#1E1B4B';
export const TEXT2 = '#6B7280';
export const BORDER = '#E9D5FF';
export const INPUT_BG = '#F5F3FF';
